# Generated by Django 6.0.1 on 2026-01-21 06:55

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', models.CharField(help_text='Primary identifier for authentication', max_length=20, unique=True)),
                ('is_owner', models.BooleanField(default=False, help_text='User can list and manage parking spots')),
                ('is_driver', models.BooleanField(default=False, help_text='User can book parking spots')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('total_bookings', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude coordinate of the parking spot')),
                ('longitude', models.FloatField(help_text='Longitude coordinate of the parking spot')),
                ('address', models.CharField(help_text='Detailed address of the parking spot', max_length=500)),
                ('city', models.CharField(default='Kathmandu', help_text='City where parking spot is located', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the parking area')),
                ('capacity_two_wheeler', models.PositiveIntegerField(help_text='Maximum number of two-wheelers', validators=[django.core.validators.MinValueValidator(1)])),
                ('capacity_four_wheeler', models.PositiveIntegerField(default=0, help_text='Maximum number of four-wheelers', validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_hour_two_wheeler', models.DecimalField(decimal_places=2, help_text='Price per hour for two-wheelers in NPR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('price_per_hour_four_wheeler', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Price per hour for four-wheelers in NPR', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('is_active', models.BooleanField(default=True, help_text='Whether spot is available for booking')),
                ('amenities', models.JSONField(blank=True, default=list, help_text='List of available amenities')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(limit_choices_to={'is_owner': True}, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('two_wheeler', 'Two Wheeler'), ('four_wheeler', 'Four Wheeler')], help_text='Type of vehicle being parked', max_length=20)),
                ('start_time', models.DateTimeField(help_text='When the parking period starts')),
                ('end_time', models.DateTimeField(help_text='When the parking period ends')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price calculated by backend (NPR)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the booking', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from driver or owner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(limit_choices_to={'is_driver': True}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.parkingspot')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParkingSpotImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Picture of the parking area', upload_to='parking_spots/%Y/%m/%d/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.parkingspot')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Detailed feedback about the parking experience')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.booking')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UtsavEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text="Name of the event/festival (e.g., 'Gai Jatra 2026')", max_length=255)),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('start_time', models.TimeField(help_text='Event start time')),
                ('end_time', models.TimeField(help_text='Event end time')),
                ('temporary_capacity_two_wheeler', models.PositiveIntegerField(help_text='Total two-wheeler capacity during event', validators=[django.core.validators.MinValueValidator(1)])),
                ('temporary_capacity_four_wheeler', models.PositiveIntegerField(default=0, help_text='Total four-wheeler capacity during event', validators=[django.core.validators.MinValueValidator(0)])),
                ('temporary_price_two_wheeler', models.DecimalField(decimal_places=2, help_text='Special price per hour for two-wheelers during event', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('temporary_price_four_wheeler', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Special price per hour for four-wheelers during event', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.TextField(blank=True, help_text='Additional event details')),
                ('is_active', models.BooleanField(default=True, help_text='Whether event is accepting bookings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spot', models.ForeignKey(help_text='Parking spot hosting the event', on_delete=django.db.models.deletion.CASCADE, related_name='utsav_events', to='api.parkingspot')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='utsav_event',
            field=models.ForeignKey(blank=True, help_text='Link to event if booking is for temporary event parking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='api.utsavevent'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='api_user_phone_n_891aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_owner'], name='api_user_is_owne_938d60_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_driver'], name='api_user_is_driv_35660b_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['owner'], name='api_parking_owner_i_f1a092_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['is_active'], name='api_parking_is_acti_8a80d0_idx'),
        ),
        migrations.AddIndex(
            model_name='parkingspot',
            index=models.Index(fields=['city'], name='api_parking_city_1af6c0_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['booking'], name='api_review_booking_468ef1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewer'], name='api_review_reviewe_e228b5_idx'),
        ),
        migrations.AddIndex(
            model_name='utsavevent',
            index=models.Index(fields=['spot'], name='api_utsavev_spot_id_169b74_idx'),
        ),
        migrations.AddIndex(
            model_name='utsavevent',
            index=models.Index(fields=['event_date'], name='api_utsavev_event_d_791281_idx'),
        ),
        migrations.AddIndex(
            model_name='utsavevent',
            index=models.Index(fields=['is_active'], name='api_utsavev_is_acti_fc0d61_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='utsavevent',
            unique_together={('spot', 'event_date')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['driver'], name='api_booking_driver__885881_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['spot'], name='api_booking_spot_id_512da7_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='api_booking_status_996dbb_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['start_time'], name='api_booking_start_t_9a2a28_idx'),
        ),
    ]
